In [4]:
import pandas as pd
data = {
    'id': [101, 102, 103, 104],
    'name': [
        'Aндрей', # первая буква A на англ.
        'Иpa', #вторая и третья буква на англ.
        'Игорь', # на русском
        'Игoрь' # o на англ.
    ]
}
df = pd.DataFrame(data)
display(df)

    id    name
0  101  Aндрей
1  102     Иpa
2  103   Игорь
3  104   Игoрь

In [5]:
letters = {
    # английская -> русская)
    'a': 'а', 'c': 'с', 'e': 'е', 'o': 'о', 'p': 'р', 'x': 'х', 'y': 'у',
    
    # английская -> русская)
    'A': 'А', 'B': 'В', 'C': 'С', 'E': 'Е', 'H': 'Н', 'K': 'К', 
    'M': 'М', 'O': 'О', 'P': 'Р', 'T': 'Т', 'X': 'Х', 'Y': 'У'
}
trans_table = str.maketrans(letters)
df['update_name'] = df['name'].str.translate(trans_table)
df = df[['id', 'update_name']]
display(df)

    id update_name
0  101      Андрей
1  102         Ира
2  103       Игорь
3  104       Игорь

In [6]:
df['new_id'] = df.groupby('update_name').ngroup()
display(df)

    id update_name  new_id
0  101      Андрей       0
1  102         Ира       2
2  103       Игорь       1
3  104       Игорь       1